### ISSUE TITLE
Service not enabled on systemd::timer

### ISSUE THREAD

**Issue by tuxmaster5000** [voxpupuli/puppet-systemd#391]
- Distribution: RHEL-8+9
- Module version: 4.1

## How to reproduce (e.g Puppet code you use)

```puppet
 systemd::timer { 'foo.timer':
  timer_source    => ...,
  service_content => template..,
  active          => true,
  enable          => true,
}
```

## What are you seeing

`systemd status foo.service`
reports, that the service is disabled.

## What behaviour did you expect instead

That the service is marked as enabled.

## Output log

```
systemctl status foo
● foo.service -foo   Loaded: loaded (/etc/systemd/system/foo.service; disabled; vendor preset: disabled)
   Active: inactive (dead) since Fri 2023-11-10 10:57:36 CET; 10s ago
  Process: 785540 ExecStart=/some/file (code=exited, status=0/SUCCESS)
 Main PID: 785540 (code=exited, status=0/SUCCESS)
```

**Comment by ekohl** [comment]
I think it enables foo.timer, which in turn will start foo.service

**Comment by tuxmaster5000** [comment]
But after an system reboot:
systemctl list-timers
will not list the timer any more.

**Comment by traylenator** [comment]
The service  has to be started either via 

1. Being enabled 
2. There being a  `OnBootSec=` type parameter in the timer so that it will do initial run.

The timer itself will be enabled on reboot , its just the first run may never happen if only using `OnUnitActiveSec=,`

So there probably is a use case for the service being enabled as well to do the first run.

It should not just be enabled with the timer being enabled since for sure having the timer enabled but not the service is also valid.

**Comment by traylenator** [comment]
systemctl enable foo.timer 

and it will be there after reboot.   Is that happening for the `enable => true` case ?

**Comment by tuxmaster5000** [comment]
Yes, "enable -> true" is set.

**Comment by traylenator** [comment]
> Yes, "enable -> true" is set.

Okay. The timer needs to be "installable" i.e it needs to have an `[Install]` section  - typically.

```ini
[Install]
WantedBy=timers.target
```
If you try enabling this timer as it is you will get a warning.

e.g.

```
# cat /lib/systemd/system/flatten-krb5.timer 
[Unit]
Description=Call flatten-krb5

[Timer]
OnBootSec=5min
OnUnitActiveSec=24h
```
results in:
```
[root@aiadm99 system]# systemctl enable flatten-krb5.timer
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled or disabled using systemctl.
 
Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.
```

After fixing the unit with and Install section all is good.


When puppet is asked to enable an un-installable unit it does not attempt it rather than it considering it to be an error I believe.

**Comment by tuxmaster5000** [comment]
I will another warning, but the source will be the same I  think:
```
systemctl enable foo.timer
Unit /etc/systemd/system/foo.timer is added as a dependency to a non-existent unit multiuser.target.
```
In my case an typo. So ash on my head.

**Comment by traylenator** [comment]
That really should be an error.

**Comment by TheMeier** [comment]
Can this be closed then? Or do you want some changes to be made @traylenator?
